## Создать тип контента
POST http://localhost:4444/api/content-type HTTP/1.1
Content-Type: application/json

{
"name": "video"
}
###
## Список публикаций
GET http://localhost:4444/api/content-type HTTP/1.1
Content-Type: application/json

###
## Обновить публикацию
PATCH http://localhost:4444/api/content-type/1 HTTP/1.1
Content-Type: application/json

{
"name": "text"
}
###
