version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-readme
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    healthcheck:
       test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-users --quiet
       interval: 10s
       timeout: 10s
       retries: 5
    volumes:
      - ./database:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-readme
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/

  rabbitmq-user:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-user
    restart: always
    ports:
      - '5674:5672'
      - '15674:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
