version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-readme
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-readme
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
