#Публикация
## Создать публикацию
POST http://localhost:4444/api/blog HTTP/1.1
Content-Type: application/json

{
"contentType": "video",
"content": {
  "postName": "bebebeb",
  "postText": "Life is life",
  "citeAuthor": "Author"
  },
"tagList": ["foor", "second", "new"]
}
###
## Список публикаций
GET http://localhost:4444/api/blog/?sortDirection=asc HTTP/1.1
Content-Type: application/json

###
## Запрос публикации
GET http://localhost:4444/api/blog/4 HTTP/1.1
Content-Type: application/json

###
## Обновление публикации
PATCH http://localhost:4444/api/blog/666 HTTP/1.1
Content-Type: application/json

{
  "content": {
  "postReview": "No problem-3"
  },
"tagList": ["bad", "dad"]
}
###
## Удаление публикации
DELETE  http://localhost:4444/api/blog/5 HTTP/1.1
Content-Type: application/json

###
## Лайк
POST http://localhost:4444/api/blog/like/1 HTTP/1.1
Content-Type: application/json

###
## Репост публикации
POST http://localhost:4444/api/blog/repost/4 HTTP/1.1
Content-Type: application/json

###


